/*
 * File: app/store/Employees.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleGridPopup.store.Employees', {
    extend: 'Ext.data.Store',

    requires: [
        'SimpleGridPopup.model.Employee',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Employees',
            model: 'SimpleGridPopup.model.Employee',
            data: [
                {
                    firstName: 'veniam',
                    lastName: 'aut',
                    phoneNumber: 'praesentium'
                },
                {
                    firstName: 'deleniti',
                    lastName: 'dolor',
                    phoneNumber: 'odit'
                },
                {
                    firstName: 'laboriosam',
                    lastName: 'consequatur',
                    phoneNumber: 'cupiditate'
                },
                {
                    firstName: 'ut',
                    lastName: 'in',
                    phoneNumber: 'et'
                },
                {
                    firstName: 'nesciunt',
                    lastName: 'aut',
                    phoneNumber: 'sapiente'
                },
                {
                    firstName: 'maxime',
                    lastName: 'aut',
                    phoneNumber: 'odio'
                },
                {
                    firstName: 'deleniti',
                    lastName: 'consequatur',
                    phoneNumber: 'et'
                },
                {
                    firstName: 'veniam',
                    lastName: 'saepe',
                    phoneNumber: 'et'
                },
                {
                    firstName: 'repellendus',
                    lastName: 'fugit',
                    phoneNumber: 'vitae'
                },
                {
                    firstName: 'sit',
                    lastName: 'id',
                    phoneNumber: 'numquam'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});