/*
 * File: app/view/AppContainer.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleGridPopup.view.AppContainer', {
    extend: 'Ext.Container',
    alias: 'widget.appcontainer',

    requires: [
        'SimpleGridPopup.view.AppContainerViewModel',
        'SimpleGridPopup.view.AppContainerViewController',
        'Ext.tab.Panel',
        'Ext.grid.Grid',
        'Ext.grid.column.Column'
    ],

    controller: 'appcontainer',
    viewModel: {
        type: 'appcontainer'
    },
    reference: 'AppContainer',
    layout: 'fit',

    items: [
        {
            xtype: 'tabpanel',
            items: [
                {
                    xtype: 'container',
                    title: 'Tab 1',
                    items: [
                        {
                            xtype: 'grid',
                            height: '100%',
                            width: '100%',
                            store: 'Employees',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'firstName',
                                    text: 'Firstname'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastName',
                                    text: 'Surname'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'phoneNumber',
                                    text: 'Number'
                                }
                            ],
                            listeners: {
                                childtap: 'onGridSelect'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    title: 'Tab 2'
                },
                {
                    xtype: 'container',
                    title: 'Tab 3'
                }
            ]
        }
    ]

});