/*
 * File: app/view/AppContainerViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleGridPopup.view.AppContainerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.appcontainer',

    onGridSelect: function(list, location, eOpts) {
        // console.log(this.lookupReference('AppContainer'));

        var myForm = Ext.create({
            xtype: 'updatepanel',
            width: 400,
            record: location.record,
            viewModel : {
                data: {
                    employee: location.record
                }
            }
        });

        myForm.show();
    }

});