/*
 * File: app/view/UpdatePanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleGridPopup.view.UpdatePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.updatepanel',

    onCancelButton: function(button, e, eOpts) {
        var view = this.getView(),
            record = view.getRecord();
        view.destroy();
        record.reject();
    },

    onSaveButton: function(button, e, eOpts) {
        var view = this.getView(),
            record = view.getRecord();
        view.destroy();
        record.commit();
    }

});